### ISSUE TITLE
Kill query broken since commit e0ebd349

### ISSUE THREAD

**Issue by anse1** [disco-stu/pg_rage_terminator#2]
Commit e0ebd349 broke the kill query, leading to the chance setting being ignored.

,----
| pg_rage_terminator.c: In function ‘pg_rage_terminator_build_query’:
| pg_rage_terminator.c:68:27: warning: too many arguments for format [-Wformat-extra-args]
`----

**Comment by psoo** [comment]
I've just created a pull request with (hopefully) all open issues addressed.

**Comment by disco-stu** [comment]
Thanks for pointing out this issue. It's fixed in commit fe2c3d17421c56292fbd667fffaab586b70dbd02 by @psoo.
